USE SCHEMA DDA;

CREATE or REPLACE TABLE STG_dim_Date
(
	DateId int NOT NULL,
	Date date NOT NULL,
	Day tinyint NOT NULL,
	DaySuffix char(2) NOT NULL,
	Weekday tinyint NOT NULL,
	WeekDayName varchar(10) NOT NULL,
	IsWeekend Integer NOT NULL,
	IsHoliday varchar NULL,
	HolidayText varchar(64) NULL,
	DOWInMonth tinyint NOT NULL,
	DayOfYear smallint NOT NULL,
	WeekOfMonth tinyint NOT NULL,
	WeekOfYear tinyint NOT NULL,
	ISOWeekOfYear tinyint NOT NULL,
	Month tinyint NOT NULL,
	MonthName varchar(10) NOT NULL,
	Quarter tinyint NOT NULL,
	QuarterName varchar(6) NOT NULL,
	Year int NOT NULL,
	MMYYYY char(6) NOT NULL,
	MonthYear varchar(10) NOT NULL,
	FirstDayOfWeek date NOT NULL,
	LastDayOfWeek date NOT NULL,
	FirstDayOfMonth date NOT NULL,
	LastDayOfMonth date NOT NULL,
	FirstDayOfQuarter date NOT NULL,
	LastDayOfQuarter date NOT NULL,
	FirstDayOfYear date NOT NULL,
	LastDayOfYear date NOT NULL,
	FirstDayOfNextMonth date NOT NULL,
	FirstDayOfNextYear date NOT NULL
);


-- CREATE TABLE STG_dim_Customer
-- (
-- 	CustomerId int IDENTITY(1,1) NOT NULL,
-- 	NonSigCode nvarchar(100) NOT NULL,
-- 	BranchCode nvarchar(100) NULL,
-- 	CustomerName nvarchar(510) NULL,
-- 	Address nvarchar(1000) NULL,
-- 	City nvarchar(510) NULL,
-- 	PhoneNumber nvarchar(100) NULL,
-- 	FaxNumber nvarchar(100) NULL,
-- 	State nvarchar(100) NULL,
-- 	PostalCode nvarchar(100) NULL,
-- 	Country varchar(2) NULL,
-- 	Latitude decimal(5, 0) NULL,
-- 	Longitude decimal(5, 0) NULL,
-- 	MonOpen nvarchar(10) NULL,
-- 	MonClose nvarchar(10) NULL,
-- 	TueOpen nvarchar(10) NULL,
-- 	TueClose nvarchar(10) NULL,
-- 	WedOpen nvarchar(10) NULL,
-- 	WedClose nvarchar(10) NULL,
-- 	ThuOpen nvarchar(10) NULL,
-- 	ThuClose nvarchar(10) NULL,
-- 	FriClose nvarchar(10) NULL,
-- 	FriOpen nvarchar(10) NULL,
-- 	SatClose nvarchar(10) NULL,
-- 	SatOpen nvarchar(10) NULL,
-- 	SunOpen nvarchar(10) NULL,
-- 	SunClose nvarchar(10) NULL,
-- 	CompCode nvarchar(50) NULL,
-- 	SalesOrg nvarchar(100) NULL,
-- 	DistributionChannel nvarchar(100) NULL,
-- 	Division nvarchar(100) NULL,
-- 	CustomerGroup nvarchar(100) NULL,
-- 	CommonOwner nvarchar(100) NULL,
-- 	SubCommonOwner nvarchar(100) NULL,
-- 	HeadOffice nvarchar(100) NULL,
-- 	TimeZone nvarchar](510) NULL,
-- 	[CommercialFlag] [bit] NULL,
-- 	[ConsumerFlag] [bit] NULL,
-- 	[OTRFlag] [bit] NULL,
-- 	[QSeriesCode] [nvarchar](50) NULL,
-- 	[TaxCode] [nvarchar](50) NULL,
-- 	[g3x] [bit] NULL,
-- 	[g3xDunlop] [bit] NULL,
-- 	[g3xKelly] [bit] NULL,
-- 	[g3xRepublic] [bit] NULL,
-- 	[g3xCommercial] [bit] NULL,
-- 	[FleetHQ] [int] NULL,
-- 	[TrailerTiresInstallation] [bit] NULL,
-- 	[StoreInventoryExist] [bit] NULL,
-- 	[GoodyearOwnControl] [bit] NULL,
-- 	[BayCount] [nvarchar](10) NULL,
-- 	[StoreManagerPhone] [nvarchar](100) NULL,
-- 	[StoreEmail] [nvarchar](100) NULL,
-- 	[StoreManagerName] [nvarchar](100) NULL,
-- 	[DistrictManagerEmail] [nvarchar](100) NULL,
-- 	[DistrictManagerName] [nvarchar](100) NULL,
-- 	[DistrictNumber] [nvarchar](100) NULL,
-- 	[RegionManagerEmail] [nvarchar](100) NULL,
-- 	[RegionManagerName] [nvarchar](100) NULL,
-- 	[RegionNumber] [nvarchar](100) NULL,
-- 	[iStore] [nvarchar](100) NULL,
-- 	[POSType] [nvarchar](50) NULL,
-- 	[PartsProvider] [nvarchar](100) NULL,
-- 	[TOW365] [bit] NULL,
-- 	[LocationType] [nvarchar](510) NULL,
-- 	[LocationTypeDescription] [nvarchar](510) NULL,
-- 	[DWMFIsWarehouse] [bit] NULL,
-- 	[TRSOnly] [bit] NULL,
-- 	[GeminiFlag] [bit] NULL,
-- 	[LCPlantCode] [nvarchar](500) NULL,
-- 	[ShuttleService] [bit] NULL,
-- 	[POSId] [nvarchar](100) NULL,
-- 	[InstallerType] [nvarchar](100) NULL,
-- 	[LastUpdatedOn] [varchar](50) NOT NULL,
-- 	[DeActivateOn] [varchar](50) NULL,
-- 	[Status] [varchar](50) NULL,
-- 	[_srcCustomerId] [uniqueidentifier] NULL,
-- 	[HubName] [varchar](50) NULL,
-- 	[MarketName] [varchar](50) NULL,
-- 	[MarketActivatedDate] [datetime] NULL,
-- 	[IsRealTimeSchedule] [bit] NULL
-- );




CREATE or REPLACE TABLE stg_fact_Mobilezipcode
(
	ZipcodeId bigint IDENTITY(1,1) NOT NULL,
	Zipcode varchar(50) NOT NULL,
	NonSig varchar(50) NOT NULL,
	StopTimeInterval varchar(50) NOT NULL,
	FixedStopDateTime int NOT NULL,
	VariableStopDateTime int NOT NULL,
	SpecialEventAddedDateTime int NOT NULL,
	WeatherAddedDateTime int NOT NULL,
	CustomerId int NOT NULL,
	CreatedDateTime date NOT NULL,
	ModifiedDateTime varchar NULL,
	EffectiveDateId int NOT NULL,
	EffectiveDateTime date NOT NULL,
	EndDateId varchar NULL,
	EndDateTime varchar NULL,
	IsCurrent varchar NOT NULL
);