Create schema demo1
CREATE TABLE STG_dim_Date
(
	DateId int NOT NULL,
	Date date NOT NULL,
	Day tinyint NOT NULL,
	DaySuffix char(2) NOT NULL,
	Weekday tinyint NOT NULL,
	WeekDayName varchar(10) NOT NULL,
	IsWeekend Integer NOT NULL,
	IsHoliday varchar NULL,
	HolidayText varchar(64) NULL,
	DOWInMonth tinyint NOT NULL,
	DayOfYear smallint NOT NULL,
	WeekOfMonth tinyint NOT NULL,
	WeekOfYear tinyint NOT NULL,
	ISOWeekOfYear tinyint NOT NULL,
	Month tinyint NOT NULL,
	MonthName varchar(10) NOT NULL,
	Quarter tinyint NOT NULL,
	QuarterName varchar(6) NOT NULL,
	Year int NOT NULL,
	MMYYYY char(6) NOT NULL,
	MonthYear varchar(10) NOT NULL,
	FirstDayOfWeek date NOT NULL,
	LastDayOfWeek date NOT NULL,
	FirstDayOfMonth date NOT NULL,
	LastDayOfMonth date NOT NULL,
	FirstDayOfQuarter date NOT NULL,
	LastDayOfQuarter date NOT NULL,
	FirstDayOfYear date NOT NULL,
	LastDayOfYear date NOT NULL,
	FirstDayOfNextMonth date NOT NULL,
	FirstDayOfNextYear date NOT NULL
)